spring:
  aop:
    proxy-target-class: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?characterEncoding=UTF-8
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxWait: 60000
    maxActive: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    
  profiles:
    active: dev
    include: redis
  #缓存配置
  redis:
    host: localhost
    port: 6379
    timeout: 3000
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 1
      max-wait: 1
      
  thymeleaf:
    cache: false
    prefix: classpath:/public/
    suffix: .html
    enabled: true
    encoding:
      utf-8
    mode: LEGACYHTML5
logging:
  pattern:
    console: "%d - %msg%n"
#    path: D:/log/
    file: D:/log/yangpan.log
    level:

mybatis:
  #指定映射文件
  mapper-locations: classpath:/mapper/*Mapper.xml
  #指定bean所在包
  type-aliases-package: com.pan.entity

    
server: 
  port: 8080 
  context-path: /

  
  
  
  

  
